#!/usr/bin/env bash
#
# Setup github action environment for testing

# Install dependencies
sudo apt-get -yqq install libpq-dev libmysqlclient-dev libsqlite3-dev

bundle install --gemfile gemfiles/ci.gemfile --jobs 4 --retry 3 --quiet
bundle exec --gemfile gemfiles/ci.gemfile rspec
