name: Run tests and linters

on: [push, pull_request]

#runs-on:


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        #os: [ubuntu-18.04]
        RAILS_VERSION: ['6.0.0', '5.2.0']
        #- 6.0.0
        #- 5.2.0
            #- 5.1.0
            #- 5.0.0
            #- 4.2.0
            #- 4.1.0
            #- 3.2.0
            #- 3.1.0

    services:
      postgres:
        image: postgres:11
        ports: ['5432:5432']
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: seed_fu_test
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Build and test
      env:
        RAILS_ENV: test
        RAILS_VERSION: ${{ matrix.RAILS_VERSION }}
        POSTGRES_HOST: localhost
        POSTGRES_USER: postgres
        POSTGRES_PASS: postgres
        POSTGRES_DB: seed_fu_test
        POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
      run: |
        sudo apt-get -yqq install libpq-dev libmysqlclient-dev libsqlite3-dev
        gem install bundler -q
        echo "what ${{ matrix.RAILS_VERSION }}"
        bundle install --gemfile gemfiles/ci.gemfile --jobs 4 --retry 3 --quiet
        DB=postgresql bundle exec --gemfile gemfiles/ci.gemfile rspec
